name: ETF Flow Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,3,6,9 * * *"   # UTC 0,3,6,9 = JST 9,12,15,18

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright
          python -m playwright install --with-deps chromium

      - name: Run ETF Flow Sentry (Playwright)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python etf_flow_sentry_playwright.py
